### PR TITLE
Drop support for Django 3.1

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Comment by pauloxnet** [comment]
Coverage seems decreased maybe some code specific for django 3.1 are not used anymore ?

**Comment by tim-schilling** [comment]
The codecov percentage is flaky. We're likely to drop it as per #1542

**Comment by tim-schilling** [comment]
Let me v3.2.4 out the door and I'll merge this.

**Review by matthiask — APPROVED** [review]
I think we could even drop Django 2.2, at least soon. 

[django-upgrade](https://pypi.org/project/django-upgrade/) may help with dropping old code afterwards.

**Comment by pauloxnet** [comment]
> _"I think we could even drop Django 2.2, at least soon."_

Not before April 2022 https://www.djangoproject.com/download/#supported-versions

**Comment by hramezani** [comment]
I think we can drop support for Django < 3.2. Here is a comment from Tim about this https://github.com/jazzband/django-hosts/pull/141#discussion_r766116557

**Comment by pauloxnet** [comment]
> No, once Django 4.0 is out, it's time to drop support for all versions older than the most recent LTS. Otherwise, it could require ugly shims to add 4.0 support (which removes a lot of deprecated things). This is outlined in https://www.djangoproject.com/weblog/2015/jun/25/roadmap/.

Thanks for pointing to this explanation. :+1:

**Pull request merged**
