### PR TITLE
 Specify code coverage as a static value. 

### PR DESCRIPTION
**Pull request by matthiask**

### CODE REVIEW

**Comment by matthiask** [comment]
@tim-schilling I added your suggestion here as a separate pull request, we can continue the discussion here.
 
cc @pauloxnet

**Review by pauloxnet — APPROVED** [review]

**Comment by pauloxnet** [comment]
@matthiask can you resolve conflicts ?

**Comment by pauloxnet** [comment]
@matthiask the PR is ready to merge. I see it's still in draft. There's a reason or you can simply  remove the draft tag ?

**Comment by matthiask** [comment]
> @matthiask the PR is ready to merge. I see it's still in draft. There's a reason or you can simply remove the draft tag ?

I opened it as a draft because I wasn't sure whether it is a good idea to hardcode the coverage percentage. I'm marking it as ready for review now because I'm basically neutral, not opposed to this.

**Comment by tim-schilling** [comment]
@matthiask what do you think about that [gist revision approach](https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa)? I'd prefer not to set it statically, but I will if it means the alternative is not having it.

**Comment by matthiask** [comment]
> @matthiask what do you think about that [gist revision approach](https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa)? I'd prefer not to set it statically, but I will if it means the alternative is not having it.

This looks interesting! I suspect that we'd need Jannis' help for this because we don't have access to the repository settings?

I'd merge this pull request and open an issue to re-investigate later if there's a better solution, maybe directly offered by GitHub or someone.

**Review by tim-schilling — APPROVED** [review]
I added a comment indicating to change the readme's coverage badge link in case we don't replace this in the future.

**Pull request merged**
