### PR TITLE
Validate duplicate middleware load

### PR DESCRIPTION
**Pull request by ad-m**
Protection for #986.

### CODE REVIEW

**Comment by kezabelle** [comment]
Looks sensible enough to me.

**Comment by matthiask** [comment]
To me as well, but the build fails with a flake8 error:
https://travis-ci.org/jazzband/django-debug-toolbar/jobs/362824956

Can you please fix this @ad-m and ping me after this?

**Comment by matthiask** [comment]
Thank you!

**Comment by blueyed** [comment]
I think this should be a warning only.
See https://github.com/jazzband/django-debug-toolbar/issues/1102.

**Pull request merged**
