### PR TITLE
Update translations for a bunch of languages.

### PR DESCRIPTION
**Pull request by tim-schilling**

### CODE REVIEW

**Comment by matthiask** [comment]
The german translations for database transaction isolation levels are terrible. I submitted new translations on Transifex and reviewed a few strings.

**Comment by tim-schilling** [comment]
@matthiask I'm not seeing the adjustments in transifex.

**Comment by tim-schilling** [comment]
@matthiask it looks like you submitted English strings for the four transaction strings for the German language. Is that correct?

**Comment by matthiask** [comment]
> 
> 
> @matthiask it looks like you submitted English strings for the four transaction strings for the German language. Is that correct?

Yes. It seemed to me that even german blog posts prefer the english terms for the transaction isolation levels. I didn't consult any textbooks (because I do not have any). But searching google and some other sites didn't help with finding good and well-known translations.

**Comment by tim-schilling** [comment]
Sounds good! Thanks for the clarification. I'll get this updated and merged
next week.

**Comment by tim-schilling** [comment]
3 weeks later...

**Pull request merged**
