### PR TITLE
Cache panel: monkey-patch caches at module level

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/django-debug-toolbar/django-debug-toolbar/issues/799.

### CODE REVIEW

**Comment by blueyed** [comment]
It's not early enough for celery though: it will have a different `caches` instance.

**Comment by tim-schilling** [comment]
Can you add a test to verify the fix for #799 to avoid regressions in the future?

**Comment by blueyed** [comment]
@tim-schilling 
Won't be easy probably, and I'm not sure if it's the right thing to do here.

**Comment by matthiask** [comment]
This should probably be closed in favor of #982?

**Pull request closed without merging**
