### PR TITLE
Handle of Composed object from psycopg2

### PR DESCRIPTION
**Pull request by stephane**
http://initd.org/psycopg/docs/sql.html#psycopg2.sql.Composed

### CODE REVIEW

**Comment by jdufresne** [comment]
Would it be possible to add a test?

**Comment by camilonova** [comment]
@stephane can you add a test?

**Comment by stephane** [comment]
Added but now running tests requires a PostgreSQL server.

**Comment by camilonova** [comment]
@aaugustin any ideas how to support this?

**Comment by aaugustin** [comment]
Provide a separate settings file that uses PostgreSQL and skip the test if not running with PostgreSQL. There are examples of doing this in Django itself.

**Pull request closed without merging**
