### PR TITLE
CachePanel: monkeypatch Django's caches across sys.modules

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/jazzband/django-debug-toolbar/issues/799.

TODO:
- [ ] cleanup (consistent naming)
- [x] test(s)

### CODE REVIEW

**Comment by matthiask** [comment]
This might work, but looks really really evil :-/

**Comment by blueyed** [comment]
Maybe https://github.com/jazzband/django-debug-toolbar/pull/800 would be less intrusive then?
I was not aware that I did another PR already when doing this one..

**Comment by camilonova** [comment]
@blueyed could you please update this PR and fix the conflicts?

**Comment by blueyed** [comment]
Would be good to get a go considering its "evil-ness" before.
/cc @matthiask @aaugustin

**Comment by aaugustin** [comment]
Aside from a general feeling that this could cause issues, I don't have a strong opinion on this. If you're ready to support users after this change, you can merge it.

**Comment by matthiask** [comment]
The relevant code has changed a lot in this area. Please resubmit if you still want to work on this. Thanks in advance!

**Pull request closed without merging**
