### PR TITLE
:wrench: update translation for Persian language

### PR DESCRIPTION
**Pull request by elias-ebrahimpour**
# Description

This pull request includes updates to the Django translation file for the Persian language. The changes aim to provide accurate and contextually appropriate translations for various strings within the Django project.

The motivation behind this update is to enhance the user experience for Persian-speaking users interacting with Django. The translation improvements cover multiple sections, ensuring that the Persian language support is more comprehensive and aligned with language conventions.

Fixes:
- debug_toolbar/locale/fa/LC_MESSAGES/django.po

### CODE REVIEW

**Comment by tim-schilling** [comment]
These look good! I'll need to upload them into transifex where our translations are managed. That may take me a bit. Thank you @elias-ebrahimpour

**Review by matthiask — APPROVED** [review]
I think we should merge this.

**Comment by tim-schilling** [comment]
We've got to upload it to transifex

**Comment by matthiask** [comment]
As I understand it we should be able to do that ourselves, after merging? But maybe not. I have to admit that I tried using transifex a long time ago, esp. the CLI, but I didn't understand it, really.

Maybe now that I wrote a much simpler version I have a better grasp of the concepts involved and could try again...

**Comment by tim-schilling** [comment]
I made an attempt in #1984.

Thanks @elias-ebrahimpour and thank you for being patient with me!

**Pull request merged**
