### PR TITLE
Introduce Prettier to format JavaScript and CSS files

### PR DESCRIPTION
**Pull request by jdufresne**
Prettier is an opinionated formatting tool for JavaScript and CSS.
Similar to how Black is for Python, Prettier automates all formatting
decisions for JS and CSS files, thus eliminating differences in
preferences. Contributors can use "make style" just like before to
restyle files.

### CODE REVIEW

**Review by tim-schilling — APPROVED** [review]
Thanks for adding this!

**Review by tim-schilling — CHANGES_REQUESTED** [review]
I didn't notice that Travis broke on the `style` test. Sorry for the extra email.

**Comment by jdufresne** [comment]
I'm a bit confused why this fails on Travis. I do not get the same error when running locally. Any ideas?

**Comment by tim-schilling** [comment]
Hmm, the additional logging was eaten somewhere. I can't reproduce this locally with node 12.16.2 that Travis claims to use.

**Comment by jdufresne** [comment]
Ah ok. This is failing because Travis runs an old version of node.js, but prettier requires 10+. I'll see what our options are here.

**Comment by jdufresne** [comment]
I have updated the Travis `dist` to `bionic`, green again :slightly_smiling_face: .

**Comment by tim-schilling** [comment]
Good find!

**Comment by matthiask** [comment]
Thanks, this is awesome! I didn't merge this yet because of all the pull requests in flight. Let's merge this when things have calmed down a bit :-)

**Comment by matthiask** [comment]
I've cherry-picked this change and re-run `prettier` on the current code in `master`. The code change is still attributed to you @jdufresne (as it should be) Thanks!

**Pull request closed without merging**
