### PR TITLE
Enabled Django 4.2 Trove classifier

### PR DESCRIPTION
**Pull request by carltongibson**
This is now available on PyPI: https://pypi.org/search/?q=&o=&c=Framework+%3A%3A+Django+%3A%3A+4.2

### CODE REVIEW

**Comment by carltongibson** [comment]
Hmmm. Still not showing up according to tox. 🤔

**Comment by tim-schilling** [comment]
This is dependent on https://github.com/pypa/hatch/pull/762 being merged.

**Comment by matthiask** [comment]
Thanks!

I've seen https://lincolnloop.com/insights/using-pyprojecttoml-in-your-django-project/ in the Django Newsletter and am wondering if the move to hatch wasn't premature after all. I've seen the other ticket and the reasoning behind it, and it makes sense to me. I also understand why `setup.py` is problematic. But the warm fuzzy feeling I had re. Python packaging in the last years (everything worked well for me) has yet to come back.

**Comment by tim-schilling** [comment]
@matthiask I'm currently out on vacation. Can you merge this and the version release PRs?

**Comment by pauloxnet** [comment]
> @matthiask I'm currently out on vacation. Can you merge this and the version release PRs?

There are some jobs that failed, so I restarted the pipeline.

**Comment by matthiask** [comment]
Thanks! Will do. The change is obviously correct, I'll fix the remaining problems on `main` (if the failures still occur)

**Comment by tim-schilling** [comment]
Thank you @matthiask!

**Comment by matthiask** [comment]
Thanks for all the preparation, I just had to press a few buttons :)

**Pull request merged**
