### PR TITLE
Fix DeprecationWarnings about form default templates

### PR DESCRIPTION
**Pull request by pfouque**
# Description

Improve [Django5 compatibility](https://github.com/jazzband/django-debug-toolbar/pull/1839) by [solving warnings related to form default templates that will change with Django5 from `table` to `div`](https://github.com/jazzband/django-debug-toolbar/issues/1813)

Fixes # (issue)

https://github.com/jazzband/django-debug-toolbar/issues/1813

# Checklist:

- [ ] I have added the relevant tests for this change.
- [ ] I have added an item to the Pending section of ``docs/changes.rst``.

### CODE REVIEW

**Review by matthiask — COMMENTED** [review]
Are we rendering table rows right now also?

`as_table` doesn't render the surrounding `<table>` element.

```django/forms/utils.py:89:    def as_table(self):
django/forms/utils.py-90-        """Render as <tr> elements excluding the surrounding <table> tag."""
django/forms/utils.py-91-        return self.render(self.template_name_table)
```

The HTML generated here isn't correct it seems to me.

**Comment by pfouque** [comment]
Weirdly, during my tests, both `as_div` and `as_table` were only rendering the `<input>`.
But I agree it would probably make more sense to use `as_div`

**Comment by tim-schilling** [comment]
It's likely because there's no need to render any additional html around a hidden input so both `.as_div` and `.as_table` are resulting in the same output. If we were to add another field input, then the problem would be realized.

**Comment by matthiask** [comment]
Maybe the time has come for us to move to `Django>=4.2`?

Django 3.2 LTS support ends this April https://www.djangoproject.com/download/

**Comment by tim-schilling** [comment]
Let's confirm there isn't anything wrong with update on fetch with @living180 first. If there isn't, I'm good with dropping 3.2 early.

**Comment by matthiask** [comment]
Yes, that's a good idea.

I have submitted https://github.com/jazzband/django-debug-toolbar/pull/1880 anyway.

**Pull request merged**
