### PR TITLE
Support Django 5.0

### PR DESCRIPTION
**Pull request by adamchainz**
# Description

Test against Django 5.0 and declare support.

# Checklist:

- [x] I have added the relevant tests for this change.
- [x] I have added an item to the Pending section of ``docs/changes.rst``.

### CODE REVIEW

**Comment by tim-schilling** [comment]
You're ahead of the testathon!

**Comment by tim-schilling** [comment]
Thanks Adam!

**Comment by adamchainz** [comment]
My life is a testathon.

**Comment by tim-schilling** [comment]
Ha! When we pitched the idea of a testathon, I suggested we market it as Adam vs The Community, in the vein of John Henry vs The Machine.

**Comment by adamchainz** [comment]
haha no way 😂

**Pull request merged**
