### PR TITLE
Refactor js

### PR DESCRIPTION
**Pull request by xi**
I would like to help refactoring the javascript code and potentially removing the jquery dependency. I know this has been discussed in #562 already. But since then, 4 years have passed and some new DOM APIs have become available. 

As a first step I did some small changes to bring the code up to modern jquery standards.

Please let me know if you are interested in this work or if there is anything else frontend-related I could help with.

### CODE REVIEW

**Comment by camilonova** [comment]
Please squash your commits. Thank you.

**Comment by jdufresne** [comment]
I think it would be great to drop the jQuery dependency! (Maybe the linked issue should be reopened.) Let me know if you need any help, I'd be happy to lend a hand wherever it could be used.

**Comment by xi** [comment]
> Please squash your commits. Thank you.

done (btw, did you know that github can do this automatically? The merge button should give you the option to do a "squash merge" instead)

**Comment by camilonova** [comment]
@xi I just surprised myself :)

**Pull request merged**
