### PR TITLE
Fix #1662: Avoid assigning arbitrary attributes to SafeString instances

### LINKED ISSUE #1662: AttributeError: 'SafeString' object has no attribute 'pygmentized'
Django Version: 4.1
Python Version: 3.10
Django Debug Toolbar Version: 3.5.0

Steps to Reproduce:
1. Open the toolbar
2. Click Templates
3. Click on a Specific Template

Screen Shot 2022-08-16 at 1 41 17 PM

```
ERROR 2022-08-16 12:29:00,535 log 82 275499009792 Internal Server Error: /__debug__/template_source/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/debug_toolbar/decorators.py", line 15, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/debug_toolbar/panels/templates/views.py", line 56, in template_source
    source.pygmentized = True
AttributeError: 'SafeString' object has no attribute 'pygmentized'
```

### PR DESCRIPTION
**Pull request by matthiask**
Refs #1662.

### CODE REVIEW

**Comment by tim-schilling** [comment]
Doesn't this need to be added to `setup.cfg`?

**Comment by matthiask** [comment]
> Doesn't this need to be added to `setup.cfg`?

It's not a mandatory dependency right now and I'm not convinced it should be. Syntax highlighting is great of course but I don't think the template panel really needs it.

**Review by tim-schilling — APPROVED** [review]
Ah, the classic "even better" solution.

**Comment by matthiask** [comment]
@tim-schilling Thanks for the review! :-)

I think it's time for another release, or is there anything we should do first?

**Comment by tim-schilling** [comment]
You're welcome! I'm good with a release.

**Pull request merged**
