### PR TITLE
stacktrace: include number of hidden frames

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by matthiask** [comment]
I had to back this change out again in my local tests -- 

```
Traceback (most recent call last):                                                              
  File "/home/matthias/Projects/sites/***/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)                                                            
  File "/home/matthias/Projects/sites/***/venv/local/lib/python2.7/site-packages/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "/home/matthias/Projects/sites/***/venv/local/lib/python2.7/site-packages/debug_panel/middleware.py", line 67, in process_response
    panel.generate_stats(request, response)                                                                                                            
  File "/home/matthias/Projects/sites/***/venv/local/lib/python2.7/site-packages/debug_toolbar/panels/sql/panel.py", line 215, in generate_stats             
    query['stacktrace'] = render_stacktrace(query['stacktrace'])                                                                                                   
  File "/home/matthias/Projects/sites/***/venv/local/lib/python2.7/site-packages/debug_toolbar/utils.py", line 72, in render_stacktrace
    trace, hidden_count = trace           
ValueError: too many values to unpack      
```

`trace` contains a HTML string it seems.

**Comment by matthiask** [comment]
I do think this change is interesting by the way, but it seems reopening pull requests after merging isn't possible.

**Comment by blueyed** [comment]
Yeah, you could have reverted it through Github's UI maybe.

I will create a new PR, but without any fix yet: https://github.com/jazzband/django-debug-toolbar/pull/1095.

**Comment by matthiask** [comment]
Oh indeed, you're right. I hadn't seen that button yet.

**Pull request merged**
