### PR TITLE
Update installation.rst

### PR DESCRIPTION
**Pull request by jwkcp**
Add urlpatterns for django version 2.0 or later

### CODE REVIEW

**Comment by jwkcp** [comment]
Yeah! I think the way you mentioned is better. Thank you for your feedback! This is my first PR. Awesome experience!

**Comment by matthiask** [comment]
Do you want to supply the change, or should I merge and change this myself? Both are fine for me, but I'd certainly prefer if you got the credits for this ✨

**Comment by matthiask** [comment]
Thanks!

**Comment by jwkcp** [comment]
I really appreciate your kind reply and guide with some tips. I will not
forget this my first tiny PR experience forever. : )
2018년 5월 9일 (수) 오후 7:56, Matthias Kestenholz <notifications@github.com>님이
작성:

**Pull request merged**
