### PR TITLE
Document serialization API for panels.

### LINKED ISSUE #1806: Add and document serialize and deserialize methods Panel API.

### PR DESCRIPTION
**Pull request by tim-schilling**
Fixes #1806 

# Checklist:

- [ ] I have added the relevant tests for this change.
- [ ] I have added an item to the Pending section of ``docs/changes.rst``.

### CODE REVIEW

**Comment by matthiask** [comment]
The lint step fails with `../debug_toolbar/panels/__init__.py:docstring of debug_toolbar.panels.Panel.deserialize_stats:1: : Spell check: Deserialize: Deserialize stats coming from the store..`

I don't know what's going on with MariaDB/MySQL.

**Comment by tim-schilling** [comment]
I don't think we're going to keep these API functions in. I'm discovering that I'd prefer to make the panel simply prepare the data in a serializable format rather than patch it in afterwards.

**Comment by tim-schilling** [comment]
Regarding mysql, I probably need to rebase on main.

**Comment by matthiask** [comment]
> I'm discovering that I'd prefer to make the panel simply prepare the data in a serializable format rather than patch it in afterwards.

Good point, makes sense to me.

**Comment by tim-schilling** [comment]
Closing

**Pull request closed without merging**
