### PR TITLE
Add testing and document support for Python 3.7

### PR DESCRIPTION
**Pull request by jdufresne**
Python 3.7 was released on June 27, 2018.

### CODE REVIEW

**Comment by matthiask** [comment]
Awesome, thanks!

**Comment by adamchainz** [comment]
@jdufresne just noticed use of `xenial` in the travis file whilst editing for #1109 . I can't find any Travis documentation about the xenial environment, how did you know it exists?

**Comment by jdufresne** [comment]
@adamchainz Best I found is https://github.com/travis-ci/travis-ci/issues/9815 which has some explanation why xenial is a necessary workaround for Python 3. 7

**Comment by adamchainz** [comment]
¯\_(ツ)_/¯ okay, will give it a try on my projects

**Pull request merged**
