### PR TITLE
Update translations and revert xgettext aliasing.

### PR DESCRIPTION
**Pull request by tim-schilling**
Aliasing xgettext causes the usage not to be picked up by makemessages.
Only gettext and gettext_lazy work with aliasing.

### CODE REVIEW

**Comment by matthiask** [comment]
Great find!

**Comment by tim-schilling** [comment]
Do you know of any good way to solicit translators?

**Comment by matthiask** [comment]
Good question ... :-/

**Comment by tim-schilling** [comment]
I suspect transifex does do notifications, but probably a good idea to solicit for some help.

**Comment by tim-schilling** [comment]
Notifications for folks who have submitted translations in the past*

**Pull request merged**
