### PR TITLE
Changed the INTERNAL_IPS CHECK

### PR DESCRIPTION
**Pull request by daveusa31**
You can set "*" in INTERNAL_IPS for access from all APIs

### CODE REVIEW

**Comment by matthiask** [comment]
Thank you for your contribution! 

We are reusing Django's `INTERNAL_IPS` setting which doesn't allow `"*"`. 

The behavior you want can already be achieved by overriding `SHOW_TOOLBAR_CALLBACK`. Maybe you could add a paragraph or two to the documentation with examples for overriding the callback?

**Comment by daveusa31** [comment]
I did this:

```python
from debug_toolbar import middleware as dt_middleware

def show_toolbar(_):
    return True
dt_middleware.show_toolbar = show_toolbar
```

**Comment by matthiask** [comment]
Adding this to your settings should do the same thing, without monkey-patching:

```python
DEBUG_TOOLBAR_CONFIG = {
    # DO NOT DEPLOY IN A LIVE ENVIRONMENT
    "SHOW_TOOLBAR_CONFIG": lambda request: True,
}
```

**Comment by daveusa31** [comment]
> Adding this to your settings should do the same thing, without monkey-patching:
> 
> ```python
> DEBUG_TOOLBAR_CONFIG = {
>     # !!!DO NOT DEPLOY IN A LIVE ENVIRONMENT!!!
>     "SHOW_TOOLBAR_CONFIG": lambda request: True,
> }
> ```
Yes, my code looks ugly.
But I tried running yours and it doesn't work

**Comment by daveusa31** [comment]
> Adding this to your settings should do the same thing, without monkey-patching:
> 
> ```python
> DEBUG_TOOLBAR_CONFIG = {
>     # !!!DO NOT DEPLOY IN A LIVE ENVIRONMENT!!!
>     "SHOW_TOOLBAR_CONFIG": lambda request: True,
> }
> ```
It should have been like this

```python
DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: True,
}
```

**Comment by matthiask** [comment]
Ah yes of course. A stupid typo by me.

**Pull request closed without merging**
