### PR TITLE
add self.assertNumQueries to test

### PR DESCRIPTION
**Pull request by crccheck**
# Description

Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context. Your commit message should include
this information as well.

Fixes # (issue)

# Checklist:

- [ ] I have added the relevant tests for this change.
- [ ] I have added an item to the Pending section of ``docs/changes.rst``.

### CODE REVIEW

**Comment by tim-schilling** [comment]
@crccheck I think this is a WIP. I'm inclined to close it to keep the open PRs minimal until there's more of a direction for the work that requires discussion/review.

**Comment by matthiask** [comment]
I think there's some value in asserting how many quietus Django sees vs how many queries the toolbar sees. I think both functionalities use the same underlying data structure, which makes this additional assertion not very useful. Or maybe I'm missing something?

**Comment by tim-schilling** [comment]
@crccheck I'm going to close this. If you feel like this is important, please let us know why and we can reopen it.

**Comment by crccheck** [comment]
oh sorry, I only opened it to see if CI would run it. I figured out how a minimal command to get tests to run locally since then and I thought draft PRs wouldn't show up

**Comment by crccheck** [comment]
FYI @matthiask there's an issue where Django's queries actually don't match Debug Toolbar #1791 I was trying to recreate

> I think there's some value in asserting how many quietus Django sees vs how many queries the toolbar sees. I think both functionalities use the same underlying data structure, which makes this additional assertion not very useful. Or maybe I'm missing something?

**Comment by tim-schilling** [comment]
Ah, that makes sense. Thanks for following up!

**Pull request closed without merging**
