### PR TITLE
Add requires.io badge to README

### PR DESCRIPTION
**Pull request by webknjaz**
Hi,

Adding a badge I was talking about.

I think it would be useful to enable notifications about outdated versions from this service.

### CODE REVIEW

**Comment by ashwoods** [comment]
@webknjaz Talking about where? I can't find the conversation.

**Comment by webknjaz** [comment]
In PR correcting dependencies

**Comment by aaugustin** [comment]
Go for it.

I'm still getting the hang of JazzBand; are you allowed to merge yourself or do I need to do something?

**Comment by webknjaz** [comment]
I don't have such permissions on this repo

**Comment by ashwoods** [comment]
@aaugustin everything is pretty much the same as any other repo, except that you have a greater `pool` of devs who can review and merge pull requests  ;)

**Comment by aaugustin** [comment]
I just noticed that the [Jazzband member] label tells me who has merge permissions.

**Comment by jezdez** [comment]
Hey all, welcome to the Jazzband :)

This isn't entirely unexpected, so don't fret, the change in this URL ironically doesn't work since it points to the old requires.io URL. The badge code should be:

```rst
.. image:: https://requires.io/github/jazzband/django-debug-toolbar/requirements.svg?branch=master
     :target: https://requires.io/github/jazzband/django-debug-toolbar/requirements/?branch=master
     :alt: Requirements Status
```

**Comment by jezdez** [comment]
Ugh, requires.io is currently working through a long task queue, so activation of that URL is taking longer than expected, in case you're seeing errors behind that URL. What a demo effect this is :)

**Pull request merged**
