### PR TITLE
Avoid stripping additional characters from GIS SQL params.

### LINKED ISSUE #1543: Some String Has Truncated Before Model Save In  Releases Version==3.2.3
#### I found some string was truncated in this function

```python
def strip_GeomFromEWKB(param):
    if isinstance(param, str):
        return param.lstrip("ST_GeomFromEWKB('\\x").rstrip("'::bytea)")
    return param
```

#### Related Pull Request

- https://github.com/jazzband/django-debug-toolbar/pull/1426

####  Minimally Reproducible Test Case

```python
In [8]: "botpy".lstrip("ST_GeomFromEWKB('\\x").rstrip("'::bytea)")
Out[8]: 'botp'

In [9]: "Botpy".lstrip("ST_GeomFromEWKB('\\x").rstrip("'::bytea)")
Out[9]: 'tp'
```

### PR DESCRIPTION
**Pull request by tim-schilling**
If the param lead or ended with characters identified in the strip
calls, those characters would also be removed. Using split will
retain all of the characters in between the given strings.

When we drop support for < 3.9, we can switch to
the removeprefix and removesuffix functions.

Fixes #1543

This should add a test case that confirms the fix for 1543, but I'm unsure of what that would look like. If we think we absolutely need a test case for it, then perhaps we move it to `panels/sql/utils.py` so it can be in a unit test rather than an integration test.

### CODE REVIEW

**Comment by tim-schilling** [comment]
Ah, this needs to not run when it's not a GIS sql param.

**Comment by matthiask** [comment]
Now that I read the code again I'm really unsure. We're modifying the SQL which is being executed instead of only logging it and maybe fixing it later when trying to analyze/explain it.

Is there a good reason for modifying the `params` list before calling `cursor.execute`, `cursor.callproc` etc. at all?

**Comment by tim-schilling** [comment]
I'm not sure. Even though the tests indicate we test for postgis, it's not used. I'm working through setting it up locally to see if the tests pass.

**Comment by tim-schilling** [comment]
@matthiask I'm going to revert #1426. I don't think it ever covered the change and the test is broken.

**Comment by tim-schilling** [comment]
Replaced by #1547

**Pull request closed without merging**
