### PR TITLE
Update documentation surrounding django.contrib.postgres.

### PR DESCRIPTION
**Pull request by tbeadle**

### CODE REVIEW

**Comment by aaugustin** [comment]
Ideally, we'd fix this bug rather than document it...

**Comment by camilonova** [comment]
@aaugustin you know if this is currently fixed?

**Comment by aaugustin** [comment]
I'm not aware of a fix.

**Comment by matthiask** [comment]
If that's still the case it would be better to add a check to `check_middleware`: https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/apps.py

**Comment by tim-schilling** [comment]
Closing this since I could not reproduce the message with Django 2.2, the lowest version the toolbar supports currently.

**Pull request closed without merging**
