### PR TITLE
Add a paragraph describing our stance on Python typing

### PR DESCRIPTION
**Pull request by matthiask**
I think we should an official paragraph to the contributing docs regarding our stance on typing. I tried describing what we're doing currently since I think it makes sense, but I'm definitely open to changing this. I don't think we should open a big round of discussions on this though.

### CODE REVIEW

**Review by tim-schilling — APPROVED** [review]
Seems fine. My issue is about adding code to silence/please people's personal environments because they have it configured differently than the baseline.

**Comment by matthiask** [comment]
Do you think we should add something to address this concern? I totally agree with you but I have a hard time finding ways to describe this without referring to particular cases.

**Comment by tim-schilling** [comment]
I don't know. It feels like it's a thing we need to commit to or not. Otherwise we end up with code like [this](https://github.com/jazzband/django-debug-toolbar/blob/main/tests/test_csp_rendering.py#L69), which I'd argue is adding code to please a configuration.

I think merging this PR is a step forward regardless.

**Comment by matthiask** [comment]
OK let's do it step by step. Thank you!

**Pull request merged**
