### PR TITLE
Drop support for Django 3.0.

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Comment by matthiask** [comment]
Thanks! Do you have any idea where the coverage decrease comes from? We cannot drop backwards compatibility shims yet because of 2.2, I'm a bit surprised that it changed anything...

**Comment by hramezani** [comment]
> Thanks! Do you have any idea where the coverage decrease comes from?

I don't know exactly. based on the report it comes from `debug_toolbar/panels/profiling.py lines 64,66,68` which seems weird to me.
After I pushed another commit it passed successfully :man_shrugging:

**Comment by hramezani** [comment]
> We cannot drop backwards compatibility shims yet because of 2.2, I'm a bit surprised that it changed anything...

The `3.0.x` series no longer receive security updates or bug fixes.

**Comment by matthiask** [comment]
> The `3.0.x` series no longer receive security updates or bug fixes.

Yes, but since we still support the older 2.2 series we cannot drop any backwards compatibility code yet.

Still, let's merge this since faster CI runs are good (tm).

**Pull request merged**
