### PR TITLE
Version 4.1.0

### PR DESCRIPTION
**Pull request by tim-schilling**
# Checklist:

- [ ] I have added the relevant tests for this change.
- [x] I have added an item to the Pending section of ``docs/changes.rst``.

### CODE REVIEW

**Comment by tim-schilling** [comment]
@matthiask I made this a minor version change due to the changes we to the monkey patching and because we're adding a configurable theming to the toolbar.

**Comment by matthiask** [comment]
Yes, thank you for preparing the release!

**Comment by ulgens** [comment]
@tim-schilling Can you please create a Github release too? Currently, it says the last release is 4.0.0. Thanks in advance 🌷

**Comment by matthiask** [comment]
@jribbens  Thanks for the report! It seems the latest commit fixed this.

**Pull request merged**
