### PR TITLE
Fix sql recording for async views

### PR DESCRIPTION
**Pull request by bellini666**

### CODE REVIEW

**Comment by tim-schilling** [comment]
It's good to see this. We'd likely need to add a test using an async view to verify this and prevent regressions.

**Comment by bellini666** [comment]
@tim-schilling yeah, I can do that.

Will check even why some tests failed saying that `ContextVar` is not callable, since is totally is.

For context, I did that change in [strawberry-django-plus](https://github.com/blb-ventures/strawberry-django-plus/blob/master/strawberry_django_plus/middlewares/debug_toolbar.py) to make sql recording work.

The only issue other than this one is that I had to disable the Template recorder. Specifically when loading the graphiql template, it triggers a database query to get current user which is not async safe (the issue does not happen if not logged in).

**Comment by tim-schilling** [comment]
Hmm, I wonder if we could replace more usages of `threading` with `contextvars`.

**Comment by matthiask** [comment]
> Hmm, I wonder if we could replace more usages of `threading` with `contextvars`.

Yes, or even with `asgiref.local.Local`.

**Comment by bellini666** [comment]
Hrm, interesting... Didn't know about `asgiref.local.Local`. Are there any advantages to it? AFAIK contextvars is basically a superior implementation that works for both threading and asyncio.

The only moment it could not be used is on python 3.6 or less, since it was released in python 3.7, but it has already reached EOL so it should not be a problem.

**Comment by bellini666** [comment]
Hey @tim-schilling , just added some tests. Don't know why postgres/postgis tests are failing though

**Comment by tim-schilling** [comment]
@matthiask I decided to copy the `database_sync_to_async` function from the channels project rather than add that as a dependency to our testing utilities. When the toolbar formally supports channels, we can switch that around.

**Comment by matthiask** [comment]
> @matthiask I decided to copy the `database_sync_to_async` function from the channels project rather than add that as a dependency to our testing utilities. When the toolbar formally supports channels, we can switch that around.

Great! Maybe the relevant utility will be added to Django itself soon. I'm not following the async database work too closely but something is happening there.

**Comment by tim-schilling** [comment]
I think this is good unless we also what to switch over the other panels to use ContextVar as well.

**Comment by bellini666** [comment]
Hey guys! Just checking if there's anything missing in this PR?

**Comment by tim-schilling** [comment]
@matthiask I'm good with thus. What do you think?

**Comment by matthiask** [comment]
Looks good to me. I haven't tested it myself and do not have much experience with async code so I still have some uncertainty, but let's move ahead with this. Thanks @bellini666 !

**Pull request merged**
