### PR TITLE
Add: response  status to HistoryPanel

### PR DESCRIPTION
**Pull request by psacawa**
See #1489

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Comment by tim-schilling** [comment]
Could you add a mention of this change in docs/changes.rst?

**Comment by tim-schilling** [comment]
I forgot to approve the CI run. Looks like the linter failed. `make style` should fix that.

**Comment by psacawa** [comment]
`make style` doesn't affect the repo for me. If further action is required, I'm happy to do it.

**Comment by tim-schilling** [comment]
Thanks @psacawa for the PR!

**Pull request merged**
